### ISSUE TITLE
[Detection summary]: Find passphrase for macOS diskutil

### ISSUE THREAD

**Issue by Weltraumschaf** [rusty-ferris-club/shellclear#58]
### Description

diskutil apfs unlockVolume /dev/XXX -passphrase YYY

**Comment by kaplanelad** [comment]
Hey @Weltraumschaf thank you for this issue.
Do you want to catch the `YYY` value like in your example?

**Comment by Weltraumschaf** [comment]
Yes, YYY is the secret passphrase to decrypt the encrypted APFS disk.

**Comment by kaplanelad** [comment]
@Weltraumschaf, thanks for this issue. 
The pattern was added to version 0.4.5

If you have any more patterns to detect, feel free to create a new issue or open a new PR for that (see #60).
