### ISSUE TITLE
[Detection summary]: URL Basic Auth false positives

### ISSUE THREAD

**Issue by MrLuje** [rusty-ferris-club/shellclear#73]
### Description

Hi, thanks for this project :)

So I installed `shellclear` for the first time today, most of my detections are related to "URL Basic Auth". Appart from false positives, I wonder if some patterns may be better in their own "pattern"

- git related urls, when using ssh, I'm not sure this should be considered as sensitive ?
```log
git clone git@github.com:MrLuje/terraform-provider-gitlab.git
git remote add upstream git@github.com:oboukili/terraform-provider-argocd.git
```
- commands with emails
```log
gpg --encrypt Brewfile --ouput encrypted.gpg --recipient bob@bob.com
git-crypt add-gpg-user --trusted bob@bob.com
git secret tell bob@bob.com
```

- false positive
```log
# no basic auth
ssh-keyscan https://www.google.com
ssh-keyscan www.google.com

# go install commands
go install github.com/atotto/clipboard@latest

# no basic auth related
rm Program.cs appsettings.Development.json appsettings.json  obj test.csproj -R wwwroot
```

**Comment by kaplanelad** [comment]
Thanks @MrLuje for reporting this issue.. 
Fix is ready in master. i'll hope to release new version in the coming days.

I'll update you once it released

**Comment by kaplanelad** [comment]
Hey @MrLuje, new version release that fixed your issue.

**Comment by MrLuje** [comment]
@kaplanelad That's perfect, many thanks !
